### ISSUE TITLE
[Feature request]: Allow forcing a canteen menu language

### ISSUE THREAD

**Issue by n1kPLV** [jxn-30/better-moodle#158]
### Geht deine Idee aus einer Problemstellung hervor? / Is your feature related to a problem?

Yes. Some moodle courses force a specific UI language and the english canteen menu sometimes isn't as detailed and/or people might not be able to comprehend these informations in a specific language.

### Lösung oder Feature / Solution or Feature

Add an options in the settings to force a specific language for the canteen menu regardless of the moodle UI language

**Comment by jxn-30** [comment]
This is online with Version `1.30.0`! :tada: :partying_face:
