### ISSUE TITLE
[BUG]: Intersex flag is not being displayed correctly

### ISSUE THREAD

**Issue by Tungdril** [jxn-30/better-moodle#212]
### Was ist passiert / What happened?

The intersex flag introduced in #208 is only displayed correctly for a split second, after that it turns solid yellow when the logo is small, and yellow with random white circles when big (login page)

### Wie kann man den Fehler reproduzieren? / How to reproduce?

1. Set setting 'Pride-Logo' to 'Intersex'
2. Wait until the page is fully loaded

### Erwartetes Verhalten / Expected behavior

Correctly displaying the Intersex SVG as the UZL-Logo mask

### System

- OS: Windows 10
- Browser: Opera GX, LVL5 (core: 109.0.5097.108)
- Better-Moodle-Version: 1.37.0

### Sonstiges / Additional

SVG is being overwritten by incorrect data:
![image](https://github.com/jxn-30/better-moodle/assets/49350541/5b290dc2-4708-4c2a-8ba3-349a4f9b225e)

The resulting logo (login):
![image](https://github.com/jxn-30/better-moodle/assets/49350541/6f53ab92-3256-46cb-b742-645f5c9c4edf)

On homepage:
![image](https://github.com/jxn-30/better-moodle/assets/49350541/719c088d-e52b-4985-bd7f-37cfc4d7b872)

**Comment by Tungdril** [comment]
A possible fix would be to use a `radial-gradient` instead of an SVG. Dark reader should not make problems, as no white is used in the flag.

```html
background-image: radial-gradient(circle,
       rgb(229, 195, 0) 0%,
       rgb(229, 195, 0) 15%,
       rgb(92 14 106) 15%,
       rgb(92 14 106) 25%,
       rgb(229, 195, 0) 25%,
       rgb(229, 195, 0) 100%);
```
Initial testing was successful, but I don't know what causes the issue in the first place. All previous testing was fine.

**Comment by jxn-30** [comment]
This seems to be a chromium-only bug in combination with DarkReader.
We may be able to avoid this by adding an `!important` to the svg rules.

**Comment by Tungdril** [comment]
Unless I'm putting it in the wrong place, `!important` doesn't seem to work, it still gets overwritten:
![image](https://github.com/jxn-30/better-moodle/assets/49350541/3e9d780a-e3ac-4fac-94db-422f01a4337c)

**Comment by Tungdril** [comment]
Further testing shows:

- The issue isn't occurring using light mode, hinting more towards DarkReader as the cause of the issue
- The issue **is** occurring on Safari in dark mode
