### ISSUE TITLE
allow filtering the dashboard sidebar per-semester

### ISSUE THREAD

**Issue by jpwiedekopf** [jxn-30/better-moodle#39]
Similar to the "My courses" view, the sidebar should allow for filtering the courses per-semester, so it doesn't get too cluttered. Most of the time, quick access to the current semester's courses should be sufficient for students and WiMis alike. It would be ideal if the filtering per-semester in the sidebar could be indepedently persisted in the user-agent's storage (this is implemented on Moodle's end for "My Courses" already), so that the sidebar could be set to "current" courses, while the "My courses" view could be set to "All" at all times - that would perfect the user experience in this regard!

**Comment by jxn-30** [comment]
If I understand correctly, that is the same as mentioned in #31, right ?

**Comment by jpwiedekopf** [comment]
My apologies, I didn't parse the issue title for #31 adequately. Yes, closing this issue as a duplicate.
