### ISSUE TITLE
[BUG]: Falsches Label für das Hovern über der Weinflasche im Mensamenü

### ISSUE THREAD

**Issue by Nicaba** [jxn-30/better-moodle#480]
### Was ist passiert / What happened?

![ohne](https://github.com/user-attachments/assets/01ec5d5d-cdd4-4ef6-b971-a290d94f1e7c)
![ohne](https://github.com/user-attachments/assets/fdb27121-dc39-4779-80c7-d55fa95c9c5c)

Moin, 
wenn man im Moodle Menü über die Weinflasche hovert steht da ohne Alkohol, auf der Studentenwerk Seite mit. 
Liebe Grüße und danke für das better-moodle
Nidal

### Wie kann man den Fehler reproduzieren? / How to reproduce?

Mit dem Mauszeiger über der Weinflasche hovern

### Erwartetes Verhalten / Expected behavior

Es sollte auch im Moodle "mit Alkohol" angezeigt werden

### System

- Betriebssystem / OS: Windows
- Browser und Version / Browser and Version: Mozilla Firefox

**Comment by jxn-30** [comment]
Oh, ich hatte einen kleinen Denkfehler drin. Wir lesen die titles der Icons aus den Filtern aus, dadurch kommt das zustande. Das ist natürlich in dem Fall blöd, weil das "ohne Alkohol" wollen wir ja eigentlich so nicht bei uns stehen haben. Aus irgend einem Grund hatte ich vorhin andersherum gedacht.

Ich schau mir das mal an, ob und wie wir das beheben können.

**Comment by jxn-30** [comment]
Um einmal meinen Denkprozess für einen Fix dokumentiert zu haben:
Auf der Seite vom Stundentenwerk hat der Filterknopf das Attribut `data-ex="1"` gesetzt, die anderen haben `data-ex="0"`. Daran können wir erkennen, ob es ein positiver oder ein negativer Filter ist.
Diese Information können wir neu mit verarbeiten, um dann den Titel entsprechend anzupassen. Wir holen uns die Texte auch direkt von der Studentenwerkseite, müssten also ein "NICHT: " davorpacken, was ich aber auch sehr unschön finde, denn `NICHT: ohne Alkohol` klingt irgendwie komisch. Die Alternative wäre, das Icon nochmal auf der Seite zu suchen, dort hat die Flasche nämlich den Titel `enthält Alkohol`.

Ich denke, mit diesen Informationen sollte ich einen Bugfix _bei Zeiten_ hinbekommen :)

**Comment by Nicaba** [comment]
Kein Stress, mir war es nur aufgefallen :)
